services:
  app:
    build: .
    ports:
      - "8501:8501"
      - "8000:8000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ipe
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 15

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    ports:
      - "18025:8025"

volumes:
  dbdata: {}
