services:
  app:
    build: .
    ports:
      - "8501:8501"
    env_file: .env
    depends_on:
      - db
      - mailhog

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ipe
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "55432:5432"

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    ports:
      - "18025:8025"

volumes:
  dbdata: {}
