version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ihracat_db
      POSTGRES_USER: ihracat_user
      POSTGRES_PASSWORD: ihracat_pass
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ihracat_user -d ihracat_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  app:
    build: .
    ports:
      - "8000:8000"
      - "8501:8501"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://ihracat_user:ihracat_pass@db:5432/ihracat_db
      - REDIS_URL=redis://redis:6379
      - PYTHONPATH=/app
    volumes:
      - .:/app
    working_dir: /app

  worker:
    build: .
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://ihracat_user:ihracat_pass@db:5432/ihracat_db
      - REDIS_URL=redis://redis:6379
      - PYTHONPATH=/app
    volumes:
      - .:/app
    working_dir: /app
    command: python -m core.worker
