name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (best effort)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # Araçlar yoksa kur (projede yoksa sorun etmesin)
          pip install --disable-pip-version-check -q flake8 pytest build || true

      # Lint (hataları raporla ama build'i kırma)
      - name: Lint - flake8 (report only)
        run: |
          echo "Running flake8..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics || true

      # Testler varsa çalıştır
      - name: Run tests (pytest if present)
        run: |
          if [ -d tests ] || [ -f pytest.ini ] || [ -f pyproject.toml ] && grep -q "\[tool.pytest.ini_options\]" pyproject.toml; then
            echo "Running pytest..."
            pytest -q
          else
            echo "No tests detected. Skipping."
          fi

      # Paketleme dosyaları varsa build et
      - name: Build package (if pyproject/setup present)
        run: |
          if [ -f pyproject.toml ] || [ -f setup.cfg ] || [ -f setup.py ]; then
            echo "Building distribution..."
            python -m build
          else
            echo "No build config. Skipping."
          fi
