name: Apply Patch (self-hosted)

on:
  workflow_dispatch:
    inputs:
      patch_b64:
        description: "Base64 olarak kodlanmış unified diff (git patch)"
        required: true
        type: string
      pr_title:
        description: "PR başlığı"
        required: true
        type: string
        default: "Apply patch via workflow"
      commit_message:
        description: "Commit mesajı"
        required: true
        type: string
        default: "chore: apply patch via workflow"
      branch:
        description: "Çalışma dalı (boş bırakılırsa otomatik isim verilir)"
        required: false
        type: string
        default: ""

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    runs-on: [self-hosted, local]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Değişkenleri hazırla
        id: vars
        shell: bash
        run: |
          set -euo pipefail
          # Kullanıcı input'u varsa onu al; yoksa GITHUB_RUN_ID ile üret
          BRANCH_INPUT="${{ inputs.branch }}"
          if [ -z "$BRANCH_INPUT" ]; then
            BRANCH_INPUT="bot/applypatch-${GITHUB_RUN_ID}"
          fi
          echo "branch=$BRANCH_INPUT" >> "$GITHUB_OUTPUT"

      - name: Yamayı çöz ve uygula
        shell: bash
        run: |
          set -euo pipefail
          echo "${{ inputs.patch_b64 }}" | base64 -d > /tmp/patch.diff
          git config user.name "artis-bot"
          git config user.email "bot@local"
          git switch -c "${{ steps.vars.outputs.branch }}"
          git apply --whitespace=fix /tmp/patch.diff

      - name: PR oluştur
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.vars.outputs.branch }}
          commit-message: ${{ inputs.commit_message }}
          title: ${{ inputs.pr_title }}
          body: |
            Applied patch via workflow.
            Triggered by: ${{ github.actor }}
