name: Artis Apply Patch

on:
  workflow_dispatch:
    inputs:
      patch:
        description: "Unified diff (patch) content"
        required: true
        type: string
      branch:
        description: "Target branch (will be created/updated)"
        required: true
        default: "artis/update-{{date}}"
        type: string
      commit_message:
        description: "Commit message"
        required: true
        default: "chore: apply patch via Artis"
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Prepare branch
        run: |
          BRANCH="${{ github.event.inputs.branch }}"
          git checkout -B "$BRANCH"

      - name: Apply patch
        shell: bash
        run: |
          cat > /tmp/changes.patch <<'PATCH_EOF'
${{ github.event.inputs.patch }}
PATCH_EOF
          # Güvenli uygulama (boşluk düzeltme)
          git apply --whitespace=fix /tmp/changes.patch

      - name: Commit
        shell: bash
        run: |
          git config user.name "artis-bot"
          git config user.email "artis-bot@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "${{ github.event.inputs.commit_message }}"

      - name: Push with PAT
        env:
          PAT: ${{ secrets.ARTIS_PAT }}
        run: |
          BRANCH="${{ github.event.inputs.branch }}"
          git push "https://x-access-token:${PAT}@github.com/${{ github.repository }}.git" HEAD:"$BRANCH"

      - name: Open or ensure PR exists
        if: ${{ always() }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ARTIS_PAT }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const head = process.env.BRANCH;
            const base = "main";
            const title = process.env.TITLE;
            async function ensurePR() {
              const existing = await github.rest.pulls.list({ owner, repo, state: "open", head: `${owner}:${head}` });
              if (existing.data.length > 0) {
                core.info("PR already exists: #" + existing.data[0].number);
                return;
              }
              await github.rest.pulls.create({
                owner, repo, head, base, title,
                body: "Automated change by Artis"
              });
              core.info("PR created.");
            }
            await ensurePR();
        env:
          BRANCH: ${{ github.event.inputs.branch }}
          TITLE: ${{ github.event.inputs.commit_message }}
