name: CD
on:
  push:
    branches: [ main ]
    paths:
      - "**/*.py"
      - "deploy/**"
      - "Dockerfile"
      - "requirements.txt"
      - "pyproject.toml"
      - ".github/workflows/cd.yml"

permissions:
  contents: read
  packages: write

env:
  ENABLE_DEPLOY: ${{ vars.ENABLE_DEPLOY }} # Settings → Actions → Variables

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deploy/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    if: ${{ env.ENABLE_DEPLOY == 'true' }}
    runs-on: [ self-hosted, prod ]
    steps:
      - name: Pull & restart container (no compose)
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest || true
          (docker rm -f app || true)
          docker run -d --name app -p 80:8000 --restart=always ghcr.io/${{ github.repository }}:latest
