name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Block committed .env
      - name: Guard .env is not tracked
        run: |
          if git ls-files --error-unmatch .env >/dev/null 2>&1; then
            echo "::error::.env is tracked in git; remove it from the repo."
            exit 1
          fi

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - run: pip install -r requirements.txt
      - run: ruff check .
      - run: black --check .

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - run: pytest -q
