name: CI
on:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install base tools
        run: |
          python -m pip install --upgrade pip
          pip install wheel
      - name: Detect & install project deps
        run: |
          set -e
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f pyproject.toml ]; then
            if grep -q "\[tool.poetry\]" pyproject.toml; then
              pip install poetry && poetry install --no-root
            else
              pip install -e .
            fi
          else
            pip install fastapi uvicorn pytest
          fi
      - name: Lint (ruff if available)
        run: |
          python - << "PY"
import importlib, sys, subprocess
mod = importlib.util.find_spec("ruff")
sys.exit(0 if (subprocess.call(["ruff","check","."])==0) else 0) if mod else print("ruff yok, atlan覺yor")
PY
      - name: Type check (mypy if available)
        run: |
          python - << "PY"
import importlib, sys, subprocess
mod = importlib.util.find_spec("mypy")
sys.exit(0 if (subprocess.call(["mypy","."])==0) else 0) if mod else print("mypy yok, atlan覺yor")
PY
      - name: Tests (pytest if tests/ exists)
        run: |
          if [ -d tests ] || ls -1 *.test.py 2>/dev/null; then
            pip install pytest pytest-cov
            pytest -q
          else
            echo "Test bulunamad覺, atlan覺yor."
          fi
